document.write( '    <footer class=\"text-white \">\n' );
document.write( '        <div class=\"container \">\n' );
document.write( '            <form action=\"\">\n' );
document.write( '                <div class=\"row\">\n' );
document.write( '                    <div class=\"address  col-lg-3\" style=\"margin-bottom: 10px\">\n' );
document.write( '                        <h2 class=\"text-light \" style=\"margin-bottom: 10px\">Address</h2>\n' );
document.write( '                        <p>123 Prize Lane<br>\n' );
document.write( '                        Kirwan, QLD</p>\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"address  col-lg-3\" style=\"margin-bottom: 10px\">\n' );
document.write( '                        <h2 class=\"text-light \" style=\"margin-bottom: 10px\">Contacts</h2>\n' );
document.write( '                        <p>0455 5555 555<br>\n' );
document.write( '                        0433 3333 333</p>\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"homeform col-lg-6\">\n' );
document.write( '                        <div class=\"form-group\">\n' );
document.write( '                            <label for=\"email\"><h2>Your Feedback:</h2></label>\n' );
document.write( '                            <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Enter email\" name=\"email\" style=\"margin-bottom: 10px\">\n' );
document.write( '                            \n' );
document.write( '                            <textarea class="form-control" placeholder="Put your feedback" rows="1" id="comment" name="text"></textarea>\n');
document.write( '                        </div>\n' );
document.write( '                        <button type=\"submit\" class=\"btn btn-outline-light\">Send</button>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '            </form>\n' );
document.write( '        </div>\n' );
document.write( '    </footer>\n' );
