document.write( '<nav id=\"navbar\" class=\"navbar navbar-expand-lg bg-dark navbar-dark sticky-top\" style=\"font-size: 110%\">\n' );
document.write( '        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\n' );
document.write( '            <span class=\"navbar-toggler-icon \"></span>\n' );
document.write( '        </button>\n' );
document.write( '        <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\n' );
document.write( '            <ul class=\"navbar-nav col-sm-10 col-md-10 col-lg-10 col-xl-11\">\n' );
document.write( '                <li style=\"margin-right: 30px\" class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"index.html">Home</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li style=\"margin-right: 30px\" class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"html/menu.html">Menu</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li style=\"margin-right: 30px\" class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"html/aboutus.html">About Us</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li style=\"margin-right: 30px\" class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"html/specials.html">Specials</a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '            <ul class=\"navbar-nav\">\n' );
document.write( '                <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"nav-link\" href=\"php/signup.php\">Sign Up</a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>\n' );
document.write( '    <script>\n' );
document.write( '    var prevScrollpos = window.pageYOffset;\n' );
document.write( '    window.onscroll = function() {\n' );
document.write( '    var currentScrollPos = window.pageYOffset;\n' );
document.write( '      if (prevScrollpos > currentScrollPos) {\n' );
document.write( '        document.getElementById(\"navbar\").style.top = \"0\";\n' );
document.write( '      } else {\n' );
document.write( '        document.getElementById(\"navbar\").style.top = \"-60px\";\n' );
document.write( '      }\n' );
document.write( '      prevScrollpos = currentScrollPos;\n' );
document.write( '    }\n' );
document.write( '    </script>' );
